# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - invenire-ai-docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://containerinvenire.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3dc9606728fb48f580f9d06608b565ad }}
        password: ${{ secrets.AzureAppService_ContainerPassword_17d689b6de6a404e9b04915c37d03813 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: containerinvenire.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3dc9606728fb48f580f9d06608b565ad }}/aliozkanozdurmus/ai-invenire:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'invenire-ai-docker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fa343ab0449344d2a0ffdc445a4a2b92 }}
        images: 'containerinvenire.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3dc9606728fb48f580f9d06608b565ad }}/aliozkanozdurmus/ai-invenire:${{ github.sha }}'